import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Libre_Barcode_39 } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const libreBarcode39 = Libre_Barcode_39({
  variable: "--font-libre-barcode-39",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Minimarket Don Ale - Sistema de Gestión",
  description: "Generated by create next app",
  icons: {
    icon: "/logo_minimarket.png",
    apple: "/logo_minimarket.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${libreBarcode39.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
